/*Redux - Sozinho*/
export const ARMAZENAR_PROCESSOS = 'ARMAZENAR_PROCESSOS';
/* */

/* Redux-Thunk */
export const BUSCAR_PROCESSOS = 'BUSCAR_PROCESSOS';
export const SETAR_PROCESSO_ATUAL = 'SETAR_PROCESSO_ATUAL';
/* */

/* Redux Saga */
export const BUSCAR_PROCESSO = 'BUSCAR_PROCESSO';
export const EXCLUIR_PROCESSO = 'EXCLUIR_PROCESSO';
export const INSERIR_PROCESSO = 'INSERIR_PROCESSO';
export const ATUALIZAR_PROCESSO = 'ATUALIZAR_PROCESSO';
export const LIMPAR_PROCESSO_ATUAL = 'SETAR_PROCESSO_ATUAL';
/* */